replicaCount: 1

image:
  repository: 971608411666.dkr.ecr.eu-north-1.amazonaws.com/frontend-hello
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: []
